# Generated by Django 6.0.4 on 2026-06-02 17:59

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_ceph', '0002_ceph_v2_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephPoolDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('size', models.PositiveSmallIntegerField(default=3)),
                ('min_size', models.PositiveSmallIntegerField(default=2)),
                ('pg_autoscale_mode', models.CharField(default='on', max_length=16)),
                ('crush_rule_name', models.CharField(blank=True, max_length=255)),
                ('application', models.CharField(default='rbd', max_length=16)),
                ('target_size_ratio', models.FloatField(blank=True, null=True)),
                ('quota_max_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quota_max_objects', models.BigIntegerField(blank=True, null=True)),
                ('compression_mode', models.CharField(default='none', max_length=16)),
                ('erasure_code_profile', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Ceph pool (desired state)',
                'verbose_name_plural': 'Ceph pools (desired state)',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CephFilesystemDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('data_pools', models.JSONField(blank=True, default=list, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('mds_placement', models.CharField(blank=True, max_length=255)),
                ('standby_count', models.PositiveSmallIntegerField(default=1)),
                ('max_mds', models.PositiveSmallIntegerField(default=1)),
                ('quota_max_bytes', models.BigIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filesystem_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('metadata_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_filesystems', to='netbox_ceph.cephpooldesiredstate')),
            ],
            options={
                'verbose_name': 'CephFS filesystem (desired state)',
                'verbose_name_plural': 'CephFS filesystems (desired state)',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cephpooldesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_ceph_pool_desired_identity'),
        ),
        migrations.AddConstraint(
            model_name='cephfilesystemdesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_ceph_filesystem_desired_identity'),
        ),
    ]
