# Generated by Django 6.0.5 on 2026-06-02 20:49

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_ceph', '0003_cephpooldesiredstate_cephfilesystemdesiredstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephRBDImageDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('pool_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('object_size', models.PositiveIntegerField(blank=True, null=True)),
                ('stripe_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('stripe_count', models.PositiveIntegerField(blank=True, null=True)),
                ('data_pool', models.CharField(blank=True, max_length=255)),
                ('clone_parent_snapshot', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('clone_parent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_children', to='netbox_ceph.cephrbdimagedesiredstate')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbd_image_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbd_image_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Ceph RBD image (desired state)',
                'verbose_name_plural': 'Ceph RBD images (desired state)',
                'ordering': ('cluster', 'pool_name', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CephRBDSnapshotDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('protected', models.BooleanField(default=False)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbd_snapshot_desired_states', to='netbox_ceph.cephcluster')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='netbox_ceph.cephrbdimagedesiredstate')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbd_snapshot_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Ceph RBD snapshot (desired state)',
                'verbose_name_plural': 'Ceph RBD snapshots (desired state)',
                'ordering': ('image', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cephrbdimagedesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'pool_name', 'name'), name='netbox_ceph_rbd_image_desired_identity'),
        ),
        migrations.AddConstraint(
            model_name='cephrbdsnapshotdesiredstate',
            constraint=models.UniqueConstraint(fields=('image', 'name'), name='netbox_ceph_rbd_snapshot_desired_identity'),
        ),
    ]
