# Generated by Django 6.0.5 on 2026-06-02 21:09

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_ceph', '0004_cephrbdimagedesiredstate_cephrbdsnapshotdesiredstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephRGWRealmDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgw_realm_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rgw_realm_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'RGW realm (desired state)',
                'verbose_name_plural': 'RGW realms (desired state)',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CephRGWUserDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('uid', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('suspended', models.BooleanField(default=False)),
                ('max_buckets', models.IntegerField(blank=True, null=True)),
                ('quota_max_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quota_max_objects', models.BigIntegerField(blank=True, null=True)),
                ('credential_ref', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgw_user_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rgw_user_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'RGW user (desired state)',
                'verbose_name_plural': 'RGW users (desired state)',
                'ordering': ('cluster', 'uid'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CephRGWBucketDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('placement_target', models.CharField(blank=True, max_length=255)),
                ('versioning_enabled', models.BooleanField(default=False)),
                ('quota_max_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quota_max_objects', models.BigIntegerField(blank=True, null=True)),
                ('lifecycle_policy', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgw_bucket_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rgw_bucket_desired_states', to='netbox_ceph.cephprovider')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buckets', to='netbox_ceph.cephrgwuserdesiredstate')),
            ],
            options={
                'verbose_name': 'RGW bucket (desired state)',
                'verbose_name_plural': 'RGW buckets (desired state)',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CephRGWZoneDesiredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('zonegroup_name', models.CharField(blank=True, max_length=255)),
                ('is_master', models.BooleanField(default=False)),
                ('endpoints', models.JSONField(blank=True, default=list, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('placement_targets', models.JSONField(blank=True, default=list, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgw_zone_desired_states', to='netbox_ceph.cephcluster')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rgw_zone_desired_states', to='netbox_ceph.cephprovider')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='netbox_ceph.cephrgwrealmdesiredstate')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'RGW zone (desired state)',
                'verbose_name_plural': 'RGW zones (desired state)',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cephrgwrealmdesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_ceph_rgw_realm_desired_identity'),
        ),
        migrations.AddConstraint(
            model_name='cephrgwuserdesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'uid'), name='netbox_ceph_rgw_user_desired_identity'),
        ),
        migrations.AddConstraint(
            model_name='cephrgwbucketdesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_ceph_rgw_bucket_desired_identity'),
        ),
        migrations.AddConstraint(
            model_name='cephrgwzonedesiredstate',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_ceph_rgw_zone_desired_identity'),
        ),
    ]
