"""Persisted models for the netbox-ceph plugin."""

from netbox_ceph.models.ceph import (
    CephCluster,
    CephCrushRule,
    CephDaemon,
    CephFilesystem,
    CephFlag,
    CephHealthCheck,
    CephOSD,
    CephPluginSettings,
    CephPool,
    CephRBDClone,
    CephRBDImage,
    CephRBDSnapshot,
    CephRGWBucketReflected,
    CephRGWPlacementTarget,
    CephRGWRealm,
    CephRGWUserReflected,
    CephRGWZone,
    CephRGWZoneGroup,
)
from netbox_ceph.models.desired_state import (
    CephFilesystemDesiredState,
    CephPoolDesiredState,
    CephRBDImageDesiredState,
    CephRBDSnapshotDesiredState,
    CephRGWBucketDesiredState,
    CephRGWRealmDesiredState,
    CephRGWUserDesiredState,
    CephRGWZoneDesiredState,
)
from netbox_ceph.models.metrics import CephMetricSnapshot
from netbox_ceph.models.operations import (
    CephDriftRecord,
    CephOperation,
    CephOperationApproval,
    CephOperationRun,
    CephPlan,
    CephValidationResult,
)
from netbox_ceph.models.providers import CephProvider

__all__ = [
    "CephCluster",
    "CephCrushRule",
    "CephDaemon",
    "CephDriftRecord",
    "CephFilesystem",
    "CephFilesystemDesiredState",
    "CephFlag",
    "CephHealthCheck",
    "CephMetricSnapshot",
    "CephOSD",
    "CephOperation",
    "CephOperationApproval",
    "CephOperationRun",
    "CephPlan",
    "CephPluginSettings",
    "CephPool",
    "CephPoolDesiredState",
    "CephProvider",
    "CephRBDClone",
    "CephRBDImage",
    "CephRBDImageDesiredState",
    "CephRBDSnapshot",
    "CephRBDSnapshotDesiredState",
    "CephRGWBucketReflected",
    "CephRGWBucketDesiredState",
    "CephRGWPlacementTarget",
    "CephRGWRealm",
    "CephRGWRealmDesiredState",
    "CephRGWUserReflected",
    "CephRGWUserDesiredState",
    "CephRGWZone",
    "CephRGWZoneGroup",
    "CephRGWZoneDesiredState",
    "CephValidationResult",
]
